name: Node.js Build Check

on: 
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
      - master
      - develop
  release:
    types:
    - created

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test --code-coverage --watch=false
      env:
        CI: true
